name: terraform-lint

on:
    push:
        branches: main

jobs:
  delivery:
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check -recursive
    
    - name: Terraform init
      id: init
      run: terraform init
    
    - name: Terraform validate
      id: validate
      run: terraform validate -no-color
