name: terraform-lint

on:
    push:
        branches: main

jobs:
  pre-commit:
    runs-on: ghcr.io/antonbabenko/pre-commit-terraform:latest

    steps:

    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Pre commit terraform tflint
      run: |
        tflint --deep --enable-rule=terraform_unused_declarations --enable-rule=terraform_unused_variables --enable-rule=terraform_deprecated_interpolation --enable-rule=terraform_documented_variables --enable-rule=terraform_documented_outputs --enable-rule=terraform_documented_inputs --enable-rule=te