name: terraform-lint

on:
    push:
        branches: main

jobs:
  delivery:
    runs-on: ghcr.io/antonbabenko/pre-commit-terraform:latest

    steps:
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Run pre-commit
      run: |
        pre-commit run --all-files
    
    - name: Pre commit terraform fmt
      run: |
        terraform fmt -check=true -diff=true -recursive
      
    - name: Pre commit terraform tflint
      run: |
        tflint --deep --enable-rule=terraform_unused_declarations --enable-rule=terraform_unused_variables --enable-rule=terraform_deprecated_interpolation --enable-rule=terraform_documented_variables --enable-rule=terraform_documented_outputs --enable-rule=terraform_documented_inputs --enable-rule=te